In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing  import OneHotEncoder
from sklearn.metrics import r2_score,root_mean_squared_error
from sklearn.pipeline import Pipeline
import pickle as pk

In [6]:
df=pd.read_csv('chennai_house_price.csv')
df[:5]

   price(in lakhs)  area  ...    location                               builder
0            37.49   872  ...   Sembakkam                         MP Developers
1            93.54  1346  ...    Selaiyur                         DAC Promoters
2           151.00  2225  ...   Mogappair     Casagrand Builder Private Limited
3            49.00  1028  ...    Ambattur                Dugar Housing Builders
4            42.28   588  ...  Pallavaram  Radiance Realty Developers India Ltd

[5 rows x 8 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2620 entries, 0 to 2619
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   price(in lakhs)  2620 non-null   float64
 1   area             2620 non-null   int64
 2   status           2620 non-null   object
 3   bhk              2620 non-null   int64
 4   bathroom         1403 non-null   float64
 5   age              1729 non-null   float64
 6   location         2620 non-null   object
 7   builder          2620 non-null   object
dtypes: float64(3), int64(2), object(3)
memory usage: 163.9+ KB

In [8]:
df.isna().sum()

price(in lakhs)       0
area                  0
status                0
bhk                   0
bathroom           1217
age                 891
location              0
builder               0
dtype: int64

In [9]:
df['age'].mean()

np.float64(1.3551185656448814)

In [10]:
df['age']=df['age'].fillna(1)
df['bathroom']=df['bathroom'].fillna(2)

In [11]:
df['bathroom'].mean()

np.float64(2.1923664122137403)

In [12]:
encoder = OneHotEncoder(drop='first', sparse_output=False)
area_encoded=encoder.fit_transform(df[['location']])
print(area_encoded[:5])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0.]]

In [13]:
cols=encoder.get_feature_names_out(['location'])

In [14]:
encoded_df = pd.DataFrame(area_encoded, columns=cols)
final_df = pd.concat([df.drop('location', axis=1), encoded_df], axis=1)

In [15]:
final_df[:5]

   price(in lakhs)  area  ... location_West Tambaram  location_tambaram west
0            37.49   872  ...                    0.0                     0.0
1            93.54  1346  ...                    0.0                     0.0
2           151.00  2225  ...                    0.0                     0.0
3            49.00  1028  ...                    0.0                     0.0
4            42.28   588  ...                    0.0                     0.0

[5 rows x 184 columns]

In [16]:
target=final_df['price(in lakhs)']
feartures=final_df.drop(['price(in lakhs)','status','builder'],axis=1)

In [17]:
x_train,x_test,y_train,y_test=train_test_split(feartures,target,train_size=0.8,random_state=42)

In [18]:
x_train[:5]

      area  bhk  ...  location_West Tambaram  location_tambaram west
1517  1152    2  ...                     0.0                     0.0
166    995    2  ...                     0.0                     0.0
1113  1218    3  ...                     0.0                     0.0
49     866    2  ...                     0.0                     0.0
729   1174    2  ...                     0.0                     0.0

[5 rows x 181 columns]

In [19]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [20]:
y_pred=model.predict(x_test)

In [21]:
acc=r2_score(y_pred,y_test)
acc

0.9149972174557585

In [22]:
root_mean_squared_error(y_pred,y_test)

34.59506696745514

In [23]:
model = Pipeline([
    ('encoder', OneHotEncoder(handle_unknown='ignore')),
    ('regressor', LinearRegression())
])

In [24]:
pk.dump(model,open('house_price_prediction.pkl','wb'))

In [25]:
pk.dump(encoder,open('encoder.pkl','wb'))